name: iOS Build

on: push

env:   
  CMAKE_VERSION: '3.31.6'
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
  XC_VERSION: ${{ '16.2' }}
  DEPLOYMENT_TARGET: '14.0'
  TRIPLET: arm64-ios
  

concurrency:
  group: ci-${{github.ref}}-ios
  cancel-in-progress: true

jobs:
  ios_build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install brew deps
        run: |
          brew uninstall cmake
          brew install automake bison flex gnu-sed autoconf-archive libtool gettext lcov openssl create-dmg mono
          brew install gnupg
          echo $(brew --prefix bison)/bin >> $GITHUB_PATH
          echo $(brew --prefix flex)/bin >> $GITHUB_PATH
          echo $(brew --prefix gettext)/bin >> $GITHUB_PATH
          
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ env.XC_VERSION }}

      - name: Install vcpkg
        shell: bash
        run: |
          mkdir -p "${{ env.VCPKG_ROOT }}"
          cd "${{ env.VCPKG_ROOT }}"
          git init
          git remote add origin https://github.com/dg0yt/vcpkg.git
          git pull origin vcpkg-make
          git checkout FETCH_HEAD
          cd "${{ env.VCPKG_ROOT }}"
          chmod +x ./bootstrap-vcpkg.sh
          ./bootstrap-vcpkg.sh

      - name: Create build system with cmake
        run: |
          mkdir -p build-mm
          cd build-mm

          # run cmake
          cmake \
            -DVCPKG_HOST_TRIPLET=arm64-osx \
            -DVCPKG_TARGET_TRIPLET=${{ env.TRIPLET }} \
            -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake \
            -D ENABLE_BITCODE=OFF \
            -D ENABLE_ARC=ON \
            -D CMAKE_CXX_VISIBILITY_PRESET=hidden \
            -D CMAKE_SYSTEM_NAME=iOS \
            -D CMAKE_SYSTEM_PROCESSOR=aarch64 \
            -D CMAKE_OSX_DEPLOYMENT_TARGET=${{ env.DEPLOYMENT_TARGET }} \
            -DIOS=TRUE \
            -DUSE_KEYCHAIN=No \
            -G "Xcode" \
            -S ${{ github.workspace }} \
            -B ./
 
      - name: Build app (release)
        run: |
          cd build-mm

          xcodebuild \
            -project Testvcpkg.xcodeproj/ \
            -scheme Testvcpkg \
            -sdk iphoneos \
            -configuration Release